### ISSUE TITLE
Create a common error response

### ISSUE THREAD

**Issue by JackyChiu** [CU-News/CU-News#35]
We should change our `reqQuery` and `reqParams` to be `givens` (Or a better word). This way we have a consistent error message. (Currently we have both due to some routes taking params and some routes taking queries)

**Comment by kirinrastogi** [comment]
I want this one!

**Comment by JackyChiu** [comment]
@kirinrastogi Go for it! It was unassigned

**Comment by kirinrastogi** [comment]
Closed by #37
