### ISSUE TITLE
Sexy Refactor - .forEach

### ISSUE THREAD

**Issue by JackyChiu** [CU-News/CU-News#44]
Refactor for promises that use `.forEach`, to use a better promise-oriented approach

**Comment by VikramBombhi** [comment]
Can you show me where this is happening so I can try fixing it

**Comment by JackyChiu** [comment]
@VikramBombhi I already assigned myself to this task, and it's multiple places

**Comment by VikramBombhi** [comment]
alright ill leave u to it
