### ISSUE TITLE
Switch primary datastore to be redis

### ISSUE THREAD

**Issue by kirinrastogi** [CU-News/CU-News#67]
This will help us scale even better. Currently, mongodb writes to disk some time after you send a request, but redis doesn't ever write to disk unless you explicitly tell it to.

This is a prerequisite for https://github.com/Branch-Bunch/Carleton-Cares/issues/11 because sorting by hot will have a lot of business logic that a fast database can handle.

**Comment by JackyChiu** [comment]
Have you considered using a javascript object to be the primary `database`? This way we can reduce network latency and take out another point of failure. I know what your thinking, "what about availability?". No worries, I read on Medium that Node.js is highly available, so our single node instance on Heroku will do just fine. 

cc: @VikramBombhi @BenEmdon @Tuanhao for opinions

**Comment by vikrambombhi** [comment]
Following up on what @JackyChiu said we could sort the properties of the object for higher efficiency. The V8 engine actually creates hidden "classes" to optimize objects so defining the properties of an object in order will actually make it faster to read/write too.

[Source](https://blog.sessionstack.com/how-javascript-works-inside-the-v8-engine-5-tips-on-how-to-write-optimized-code-ac089e62b12e)

**Comment by VikramBombhi** [comment]
Following up on what @JackyChiu said we could sort the properties of the object for higher efficiency. The V8 engine actually creates hidden "classes" to optimize objects so defining the properties of an object in order will actually make it faster to read/write too.

[Source](https://blog.sessionstack.com/how-javascript-works-inside-the-v8-engine-5-tips-on-how-to-write-optimized-code-ac089e62b12e)
