### ISSUE TITLE
Add votes and their time onto each keyword when an article is voted on.

### ISSUE THREAD

**Issue by kirinrastogi** [CU-News/CU-News#7]
:peach: only
Currently, the votes are not counted towards a keyword when an article is voted on. They need to be stored the same was as described in our model.
```
[Object]
```
Where Object contains the keys ```sum``` and ```time```

**Comment by JackyChiu** [comment]
So the client could be sending something like this:
```javascript
{
  "id": "sjkdhgvbksdjvb132r234",
  "vote": "1",
  "time": "some date string"
}
```
The sum is something you would want to calculate on the server since the client might now have the newest sum

**Comment by kirinrastogi** [comment]
Yes, but like you said earlier to me, the client doesn't need to send the time.

**Comment by JackyChiu** [comment]
👍 didn't realize this was a database job
